# Generated by Django 4.2.16 on 2024-09-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Тип нерухомості')),
            ],
            options={
                'verbose_name': 'Тип нерухомості',
                'verbose_name_plural': 'Тип нерухомості',
                'db_table': 'building_type',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Назва')),
                ('price', models.IntegerField(null=True, verbose_name='Ціна')),
                ('speed', models.CharField(max_length=100, null=True, verbose_name='Швидкість')),
                ('text', models.TextField(null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Бізнес тариф',
                'verbose_name_plural': 'Бізнес тарифи',
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Райони',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='TariffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категорія тарифів')),
            ],
            options={
                'verbose_name': 'Категорію тарифів',
                'verbose_name_plural': 'Категорії тарифів',
                'db_table': 'tariff_category',
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Назва')),
                ('price', models.IntegerField(null=True, verbose_name='Ціна')),
                ('speed', models.CharField(max_length=100, null=True, verbose_name='Швидкість')),
                ('text', models.TextField(null=True, verbose_name='Опис')),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.buildingtype', verbose_name='Тип нерухомості')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.region', verbose_name='Район')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariffcategory', verbose_name='Категорія тарифів')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'db_table': 'tariff',
            },
        ),
    ]
