# Generated by Django 4.2.16 on 2024-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment', verbose_name='Зображення методу оплати'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на оплату'),
        ),
    ]
