# Generated by Django 4.2.16 on 2024-09-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, null=True, unique=True, verbose_name='URL')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публікації')),
                ('image', models.ImageField(null=True, upload_to='blog', verbose_name='Зображення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Статтю',
                'verbose_name_plural': 'Статті',
                'db_table': 'article',
                'ordering': ['-date'],
            },
        ),
    ]
